FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG OPENAI_API_KEY
ARG AWS_BUCKET_NAME
ARG AWS_REGION
ARG RDS_DATABASE
ARG RDS_HOST
ARG RDS_PASSWORD
ARG RDS_PORT
ARG RDS_USER

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}
ENV RDS_DATABASE=${RDS_DATABASE}
ENV RDS_HOST=${RDS_HOST}
ENV RDS_PASSWORD=${RDS_PASSWORD}
ENV RDS_PORT=${RDS_PORT}
ENV RDS_USER=${RDS_USER}

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]

