name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  push_to_ecr:
    name: Build and Push FastAPI Docker Image to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::203918847795:role/git_IAM
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Ensure Docker CLI is using default builder
        run: |
          docker buildx use default || docker buildx create --use

      - name: Verify GitHub Secrets
        run: |
          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then
            echo "Error: AWS_ACCESS_KEY_ID is not set in GitHub Secrets" && exit 1
          fi
          if [[ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
            echo "Error: AWS_SECRET_ACCESS_KEY is not set in GitHub Secrets" && exit 1
          fi
          if [[ -z "${{ secrets.OPENAI_API_KEY }}" ]]; then
            echo "Error: OPENAI_API_KEY is not set in GitHub Secrets" && exit 1
          fi

      - name: Build Docker Image with Secrets
        run: |
          docker build \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -t bitenews .

      - name: Tag Docker Image
        run: |
          docker tag bitenews:latest 203918847795.dkr.ecr.ap-northeast-2.amazonaws.com/bitenews:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 203918847795.dkr.ecr.ap-northeast-2.amazonaws.com/bitenews:latest

