name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::203918847795:role/git_IAM
          aws-region: ap-northeast-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-northeast-2

      - name: Build and Push Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_USER: ${{ secrets.RDS_USER }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}       # 예: bitenews
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}           # 예: 203918847795.dkr.ecr.ap-northeast-2.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg AWS_ACCESS_KEY_ID \
            --build-arg AWS_SECRET_ACCESS_KEY \
            --build-arg OPENAI_API_KEY \
            --build-arg AWS_BUCKET_NAME \
            --build-arg AWS_REGION \
            --build-arg RDS_DATABASE \
            --build-arg RDS_HOST \
            --build-arg RDS_PASSWORD \
            --build-arg RDS_PORT \
            --build-arg RDS_USER \
            -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

